apiVersion: apps/v1
kind: Deployment
metadata:
  name: auctions-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auctions
  template:
    metadata:
      labels:
        app: auctions
    spec:
      containers:
        - name: auctions
          image: coderfemi/auctions
          env:
            - name: MONGO_URI
              value: 'mongodb://auctions-mongo-srv:27017/auctions'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auctions-srv
spec:
  selector:
    app: auctions
  ports:
    - name: auctions
      protocol: TCP
      port: 3000
      targetPort: 3000