name: deploy-manifests
on:
  push:
    branches:
      - main
    paths:
      - 'closet-sweep/infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save closet-sweep-cluster
      - run: kubectl apply -f closet-sweep/infra/k8s