name: closetsweep-tests
on: pull_request
jobs:
  test:
    name: PR Test
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: [closetsweep/auth, closetsweep/expiration, closetsweep/deals, closetsweep/orders, closetsweep/payments] }
    steps:
      - uses: actions/checkout@v2
      
      - name: Open Working Directory
        working-directory: ${{ matrix.dir }}
        run: ls -la
        
      - name: Run Tests
        run: | 
          npm install
          npm run test:ci
