name: tests-payments

on:
  pull_request:
    paths:
      - 'closet-sweep/payments/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run auth service tests
        run: cd closet-sweep/payments && npm install && npm run test:ci
