name: tests-orders

on:
  pull_request:
    paths:
      - 'closet-sweep/orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run auth service tests
        run: cd closet-sweep/orders && npm install && npm run test:ci
