name: tests-deals

on:
  pull_request:
    paths:
      - 'closet-sweep/deals/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run deals service tests
        run: cd closet-sweep/deals && npm install && npm run test:ci
